name: CI

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    uses: anthony-openclassroom/device34-cicd/.github/workflows/template-test.yml@main
    with:
      project-type: angular

  build:
    needs: test
    uses: anthony-openclassroom/device34-cicd/.github/workflows/template-build.yml@main
    permissions:
      contents: read
      packages: write

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: anthony-openclassroom/device34-cicd/.github/workflows/template-release.yml@main
    with:
      extra-plugins: |
        @semantic-release/changelog
        @semantic-release/git
        @semantic-release/npm
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
